# Generated by Django 3.0.8 on 2020-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='password',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
