# Generated by Django 3.0.8 on 2020-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200718_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.TextField(default='guest'),
        ),
    ]
