# Generated by Django 2.1.1 on 2020-08-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
