# Generated by Django 3.0.8 on 2020-07-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200716_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='postdate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
