# Generated by Django 3.0.8 on 2020-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200716_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
